# This plugin is meant for fairly vanilla servers.
# If you want more robust recipe configuration or protection against glitches/exploits
# from other plugins, consider using a dedicated custom recipe or custom item plugin.

# The name of the diamond nugget item, must be 1-50 characters
# & codes supported, see https://minecraft.fandom.com/wiki/Formatting_codes for a list
# Changing the name will make existing nuggets unable to be combined back into a diamond
# unless the player renames the nuggets back to the new name
item-name: "&fDiamond Nugget"

# The nugget material used to represent diamond nuggets, cannot be air or an unstackable item
# Changing the material will make existing nuggets unable to be combined back into a diamond
#
# Nugget items cannot be accidentally placed, used by right-clicking, or used in crafting except for:
# - Powering a beacon
# - Using an item as a brewing stand ingredient
# - Fueling a brewing stand with blaze powder
# - Mobs being attracted to and picking up items
# - Shenanigans from other plugins
# due to Spigot limitations
#
# See the link below for a list of possible materials
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# GOLD_NUGGET (beware piglins), IRON_NUGGET, AMETHYST_SHARD (1.17+), or ECHO_SHARD (1.19+) recommended
item-material: GOLD_NUGGET

# The lore of the diamond nugget item
# & codes supported
# Changing the lore will make existing nuggets unable to be combined back into a diamond
item-lore: false
lore-lines:
  - "&rLore line 1"
  - "&rLore line 2"

# The enchantments of the diamond nugget item, in "enchantment:level" format.
# Enchantment level must be 1 or higher
# See https://www.digminecraft.com/lists/enchantment_list_pc.php for a list.
# If the resource pack does not use custom model data,
# the item must have at least one enchantment for the CIT resource pack to work.
# Changing the enchantments will make existing nuggets unable to be combined back into a diamond.
item-enchanted: true
item-enchants:
  - "fortune:3"

# A list of item flags used to hide the item's attributes
# See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html for a list
# The nugget item is unbreakable, so HIDE_UNBREAKABLE recommended
# Changing the flags will make existing nuggets unable to be combined back into a diamond
item-flagged: true
item-flags:
  - HIDE_ENCHANTS
  - HIDE_UNBREAKABLE

# The amount of nuggets needed to craft a diamond
# Must be between 1-9, 4 or 9 is recommended
# 1-4 nuggets will fit in the 2x2 crafting grid
# All recipes are shaped due to vanilla limitations
nuggets-to-diamond: 9

# The recipe book category to put the recipes in
# One of BUILDING, REDSTONE, EQUIPMENT, or MISC (default)
# Only works in versions 1.19.3 and later
recipe-book-category: MISC

# Whether the recipes unlock on join (or plugin enable) regardless of what items the player has
# If false, players will unlock the recipes when picking up a diamond or diamond nugget
unlock-on-join: true

# Whether to stop players from trying to rename diamond nuggets
# Due to Minecraft recipe limitations, the *exact* item NBT must match for a custom recipe to succeed,
# so renaming the item will cause it to not work anymore in recipes
# Players can still rename regular golden nuggets, but these cannot be used to craft diamonds
prevent-renames: true

# The message to display when a player is stopped from renaming diamond nuggets
rename-disabled-message: "Renaming diamond nuggets is disabled due to Minecraft recipe limitations"

# Whether to stop players from crafting other items with diamond nuggets
prevent-crafting: true

# Whether to completely stop players from placing nuggets in a
# stonecutter, cartography table, loom, anvil, grindstone, or villager trading menu.
# This will also prevent placement in brewing stands, but players can bypass it by glitching.
#
# When true, players will not be able to place nuggets in the above menus, but won't be able to shift click
# nuggets while one of these menus is open, even if the nugget would normally be shifted into the hotbar.
# When false, the crafting/trading output will appear if the nugget forms a valid recipe, but players
# will not be able to click the result and put it into their inventory.
# Note that it is possible for players to glitch nuggets into the inventory, but cannot get the crafting result.
#
# Set to false if you are using one of the recommended nugget items.
prevent-placement: false

# The custom model data ID to use for the nugget item.
# This is used to give the item a unique model when using the resource pack.
# Changing or disabling this value will make existing nuggets unable to be combined back into a diamond.
#
# custom-model-data has 3 options:
# - Set to a string in quotes ("").
#     Only items with the exact same string will have the same texture.
#     Requires 1.21.4 or later.
# - Set to an integer without quotes.
#     All items with a bigger or equal number will have the same texture (unless overridden by another custom model data).
#     Equivalent to the behavior before 1.21.4.
# - Set to -1 to disable.
#     The resource pack will use the old method that requires Optifine or CIT Resewn.
custom-model-data: "tis:diamond_nugget"

# The pack format number put in pack.mcmeta when generating the diamond nugget resource pack.
# Set to -1 to use the pack format number for the **plugin's** current version.
# See https://minecraft.fandom.com/wiki/Resource_pack#Pack_format
# If your server allows players to join with older versions, set this to the pack format for the oldest version.
#
# Note that if custom model data is enabled, resource packs generated in 1.21.4 and later are incompatible with
# older clients. If this is the case, pack-format must be 46 or higher.
pack-format: -1
