# The name of the diamond nugget item
# Changing the name will make existing nuggets unable to be combined back into a diamond
# unless the player renames them to the new name
item-name: "Diamond Nugget"

# Whether the recipes unlock on join (or plugin enable) regardless of what items the player has
# If false, players will unlock the recipes when picking up a diamond or diamond nugget
unlock-on-join: true

# Whether to stop players from trying to rename diamond nuggets
# Due to Minecraft recipe limitations, the *exact* item NBT must match for a custom recipe to succeed,
# so renaming the item will cause it to not work anymore in recipes
# Players can still rename regular golden nuggets,
# but renaming golden nuggets to diamond nuggets will not work in recipes
prevent-renames: true

# The message to display when a player is stopped from renaming diamond nuggets
rename-disabled-message: "Renaming diamond nuggets is disabled due to Minecraft recipe limitations"
