# The name of the diamond nugget item, must be 1-50 characters
# Changing the name will make existing nuggets unable to be combined back into a diamond
# unless the player renames them to the new name
item-name: "Diamond Nugget"

# The nugget material used to represent diamond nuggets, cannot be air
# Nugget items cannot be placed or used by accident
# See the link below for a list
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
item-material: GOLD_NUGGET

# The amount of nuggets needed to craft a diamond
# Must be between 1-9, 8 or 9 is recommended
nuggets-to-diamond: 9

# Whether the recipes unlock on join (or plugin enable) regardless of what items the player has
# If false, players will unlock the recipes when picking up a diamond or diamond nugget
unlock-on-join: true

# Whether to stop players from trying to rename diamond nuggets
# Due to Minecraft recipe limitations, the *exact* item NBT must match for a custom recipe to succeed,
# so renaming the item will cause it to not work anymore in recipes
# Players can still rename regular golden nuggets, but these cannot be used to craft diamonds
prevent-renames: true

# The message to display when a player is stopped from renaming diamond nuggets
rename-disabled-message: "Renaming diamond nuggets is disabled due to Minecraft recipe limitations"
